from __future__ import annotations

import argparse
import getpass
import json
import os
import re
import sqlite3
import sys
from collections import defaultdict, deque
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Iterable
from urllib.parse import quote


@dataclass
class Column:
    name: str
    declared_type: str
    not_null: bool
    default: Any
    pk_order: int


@dataclass
class ForeignKey:
    id: int
    seq: int
    ref_table: str
    from_col: str
    to_col: str
    on_update: str
    on_delete: str


def qi(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def pg_type(declared: str, is_single_integer_pk: bool) -> str:
    t = (declared or '').strip().upper()
    if is_single_integer_pk:
        return 'BIGINT GENERATED BY DEFAULT AS IDENTITY'
    if 'INT' in t:
        return 'BIGINT'
    if any(x in t for x in ('REAL', 'FLOA', 'DOUB')):
        return 'DOUBLE PRECISION'
    if any(x in t for x in ('NUM', 'DEC')):
        return 'NUMERIC'
    if 'BLOB' in t:
        return 'BYTEA'
    if 'BOOL' in t:
        return 'BOOLEAN'
    # Keep application date/time values as text for exact compatibility with existing code.
    return 'TEXT'


def normalize_default(value: Any) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    upper = text.upper()
    if upper in {'CURRENT_TIMESTAMP', 'CURRENT_DATE', 'CURRENT_TIME'}:
        return upper
    if re.fullmatch(r'-?\d+(?:\.\d+)?', text):
        return text
    if (text.startswith("'") and text.endswith("'")) or (text.startswith('"') and text.endswith('"')):
        inner = text[1:-1].replace("'", "''")
        return f"'{inner}'"
    # SQLite expressions can be incompatible; preserve common literals and skip unknown expressions.
    return None


def table_names(conn: sqlite3.Connection) -> list[str]:
    return [
        r[0]
        for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
    ]


def columns(conn: sqlite3.Connection, table: str) -> list[Column]:
    return [Column(r[1], r[2] or '', bool(r[3]), r[4], int(r[5])) for r in conn.execute(f'PRAGMA table_info({qi(table)})')]


def foreign_keys(conn: sqlite3.Connection, table: str) -> list[ForeignKey]:
    return [ForeignKey(int(r[0]), int(r[1]), r[2], r[3], r[4], r[5], r[6]) for r in conn.execute(f'PRAGMA foreign_key_list({qi(table)})')]


def unique_indexes(conn: sqlite3.Connection, table: str) -> list[tuple[str, list[str]]]:
    out: list[tuple[str, list[str]]] = []
    for row in conn.execute(f'PRAGMA index_list({qi(table)})'):
        idx_name, is_unique, origin = row[1], bool(row[2]), row[3]
        if not is_unique or origin == 'pk':
            continue
        cols = [x[2] for x in conn.execute(f'PRAGMA index_info({qi(idx_name)})') if x[2] is not None]
        if cols:
            out.append((idx_name, cols))
    return out


def dependency_order(conn: sqlite3.Connection, tables: list[str]) -> list[str]:
    deps: dict[str, set[str]] = {t: set() for t in tables}
    reverse: dict[str, set[str]] = defaultdict(set)
    known = set(tables)
    for t in tables:
        for fk in foreign_keys(conn, t):
            if fk.ref_table in known and fk.ref_table != t:
                deps[t].add(fk.ref_table)
                reverse[fk.ref_table].add(t)
    q = deque(sorted(t for t in tables if not deps[t]))
    ordered: list[str] = []
    while q:
        t = q.popleft()
        ordered.append(t)
        for child in sorted(reverse[t]):
            deps[child].discard(t)
            if not deps[child] and child not in ordered and child not in q:
                q.append(child)
    # Cycles are safe because FKs are added after data import.
    ordered.extend(sorted(t for t in tables if t not in ordered))
    return ordered


def create_table_sql(conn: sqlite3.Connection, table: str) -> str:
    cols = columns(conn, table)
    pk_cols = sorted((c.pk_order, c.name) for c in cols if c.pk_order)
    single_integer_pk = len(pk_cols) == 1 and 'INT' in next(c.declared_type.upper() for c in cols if c.name == pk_cols[0][1])
    definitions: list[str] = []
    for c in cols:
        typ = pg_type(c.declared_type, single_integer_pk and c.name == pk_cols[0][1])
        parts = [qi(c.name), typ]
        if c.not_null and not (single_integer_pk and c.name == pk_cols[0][1]):
            parts.append('NOT NULL')
        default = normalize_default(c.default)
        if default is not None:
            parts.append('DEFAULT ' + default)
        definitions.append(' '.join(parts))
    if pk_cols:
        definitions.append('PRIMARY KEY (' + ', '.join(qi(name) for _, name in pk_cols) + ')')
    return f'CREATE TABLE {qi(table)} (\n  ' + ',\n  '.join(definitions) + '\n)'


def fk_sql(table: str, fk_group: list[ForeignKey]) -> str:
    fk_group = sorted(fk_group, key=lambda x: x.seq)
    from_cols = ', '.join(qi(x.from_col) for x in fk_group)
    to_cols = ', '.join(qi(x.to_col) for x in fk_group)
    ref = qi(fk_group[0].ref_table)
    name = f"fk_{table}_{fk_group[0].id}"
    sql = f'ALTER TABLE {qi(table)} ADD CONSTRAINT {qi(name)} FOREIGN KEY ({from_cols}) REFERENCES {ref} ({to_cols})'
    on_delete = fk_group[0].on_delete.upper()
    on_update = fk_group[0].on_update.upper()
    if on_delete and on_delete != 'NO ACTION':
        sql += ' ON DELETE ' + on_delete
    if on_update and on_update != 'NO ACTION':
        sql += ' ON UPDATE ' + on_update
    return sql


def build_plan(conn: sqlite3.Connection) -> dict[str, Any]:
    tables = table_names(conn)
    order = dependency_order(conn, tables)
    counts = {t: int(conn.execute(f'SELECT COUNT(*) FROM {qi(t)}').fetchone()[0]) for t in tables}
    return {'tables': tables, 'order': order, 'counts': counts, 'rows_total': sum(counts.values())}


def connection_url_from_prompt() -> str:
    existing = os.environ.get('DATABASE_URL', '').strip()
    if existing:
        return existing
    password = getpass.getpass('Supabase database password: ')
    if not password:
        raise SystemExit('Password was empty.')
    project_ref = os.environ.get('SUPABASE_PROJECT_REF', 'udczeoltolukwxxmkkpa')
    host = os.environ.get('SUPABASE_DB_HOST', 'aws-0-eu-west-1.pooler.supabase.com')
    user = os.environ.get('SUPABASE_DB_USER', f'postgres.{project_ref}')
    return f'postgresql://{user}:{quote(password, safe="")}@{host}:5432/postgres'


def batches(rows: Iterable[tuple[Any, ...]], size: int = 500):
    batch: list[tuple[Any, ...]] = []
    for row in rows:
        batch.append(tuple(row))
        if len(batch) >= size:
            yield batch
            batch = []
    if batch:
        yield batch


def migrate(sqlite_path: Path, database_url: str, reset: bool, dry_run: bool, report_path: Path) -> dict[str, Any]:
    source = sqlite3.connect(sqlite_path)
    source.row_factory = sqlite3.Row
    plan = build_plan(source)
    report: dict[str, Any] = {
        'started_at': datetime.now().isoformat(timespec='seconds'),
        'sqlite_path': str(sqlite_path),
        'table_count': len(plan['tables']),
        'source_rows_total': plan['rows_total'],
        'tables': {},
        'status': 'dry-run' if dry_run else 'running',
    }
    print(f"Found {len(plan['tables'])} tables and {plan['rows_total']} rows.")
    if dry_run:
        for t in plan['order']:
            report['tables'][t] = {'source_rows': plan['counts'][t], 'ddl': create_table_sql(source, t)}
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')
        return report

    try:
        import psycopg
    except ImportError as exc:
        raise SystemExit('Install dependency first: python -m pip install "psycopg[binary]"') from exc

    target = psycopg.connect(database_url, sslmode='require', connect_timeout=30)
    try:
        with target.cursor() as cur:
            cur.execute("SELECT pg_advisory_lock(9061002)")
            if reset:
                print('Reset mode: dropping existing public tables...')
                cur.execute("SELECT tablename FROM pg_tables WHERE schemaname='public'")
                existing = [r[0] for r in cur.fetchall()]
                for t in existing:
                    cur.execute(f'DROP TABLE IF EXISTS {qi(t)} CASCADE')
            else:
                cur.execute("SELECT tablename FROM pg_tables WHERE schemaname='public'")
                existing = [r[0] for r in cur.fetchall() if r[0] in plan['tables']]
                if existing:
                    raise RuntimeError('Target already contains ERP tables. Re-run with --reset only if you intend to replace them: ' + ', '.join(existing[:10]))

            print('Creating tables...')
            for t in plan['order']:
                cur.execute(create_table_sql(source, t))

            print('Copying data...')
            for index, t in enumerate(plan['order'], start=1):
                cols = columns(source, t)
                names = [c.name for c in cols]
                count = plan['counts'][t]
                if count:
                    placeholders = ', '.join(['%s'] * len(names))
                    insert_sql = f'INSERT INTO {qi(t)} (' + ', '.join(qi(n) for n in names) + f') VALUES ({placeholders})'
                    src_cur = source.execute(f'SELECT ' + ', '.join(qi(n) for n in names) + f' FROM {qi(t)}')
                    for batch in batches(src_cur, 500):
                        cur.executemany(insert_sql, batch)
                report['tables'][t] = {'source_rows': count, 'copied_rows': count}
                print(f'[{index}/{len(plan["order"])}] {t}: {count}')

            print('Creating unique indexes...')
            for t in plan['order']:
                for idx_name, idx_cols in unique_indexes(source, t):
                    safe_name = idx_name if not idx_name.startswith('sqlite_autoindex') else f'uq_{t}_{"_".join(idx_cols)}'
                    cur.execute(f'CREATE UNIQUE INDEX IF NOT EXISTS {qi(safe_name)} ON {qi(t)} (' + ', '.join(qi(c) for c in idx_cols) + ')')

            print('Adding foreign keys...')
            for t in plan['order']:
                groups: dict[int, list[ForeignKey]] = defaultdict(list)
                for fk in foreign_keys(source, t):
                    groups[fk.id].append(fk)
                for group in groups.values():
                    cur.execute(fk_sql(t, group))

            print('Synchronizing identity sequences...')
            for t in plan['order']:
                cols = columns(source, t)
                pk_cols = [c for c in cols if c.pk_order]
                if len(pk_cols) == 1 and 'INT' in pk_cols[0].declared_type.upper():
                    col = pk_cols[0].name
                    cur.execute("SELECT pg_get_serial_sequence(%s, %s)", (t, col))
                    seq = cur.fetchone()[0]
                    if seq:
                        cur.execute(f'SELECT COALESCE(MAX({qi(col)}), 0) FROM {qi(t)}')
                        max_id = int(cur.fetchone()[0])
                        cur.execute("SELECT setval(%s, %s, %s)", (seq, max(max_id, 1), max_id > 0))

            print('Validating row counts...')
            for t in plan['order']:
                cur.execute(f'SELECT COUNT(*) FROM {qi(t)}')
                target_count = int(cur.fetchone()[0])
                report['tables'][t]['target_rows'] = target_count
                if target_count != plan['counts'][t]:
                    raise RuntimeError(f'Row-count mismatch for {t}: source={plan["counts"][t]}, target={target_count}')

            cur.execute("SELECT pg_advisory_unlock(9061002)")
        target.commit()
        report['status'] = 'success'
        report['finished_at'] = datetime.now().isoformat(timespec='seconds')
        report['target_rows_total'] = sum(x['target_rows'] for x in report['tables'].values())
        print('SUCCESS: schema and data migrated to Supabase PostgreSQL.')
        return report
    except Exception:
        target.rollback()
        report['status'] = 'failed'
        report['finished_at'] = datetime.now().isoformat(timespec='seconds')
        raise
    finally:
        target.close()
        source.close()
        report_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding='utf-8')


def main() -> int:
    parser = argparse.ArgumentParser(description='Migrate Pharma ERP SQLite database to Supabase PostgreSQL.')
    parser.add_argument('--sqlite', default='pharmacy_finance.db', help='Path to SQLite database.')
    parser.add_argument('--database-url', default='', help='PostgreSQL URL. Prefer DATABASE_URL environment variable.')
    parser.add_argument('--reset', action='store_true', help='Drop existing public tables before migration.')
    parser.add_argument('--dry-run', action='store_true', help='Analyze source and generate a report without connecting.')
    parser.add_argument('--report', default='SUPABASE_MIGRATION_REPORT.json')
    args = parser.parse_args()

    sqlite_path = Path(args.sqlite).expanduser().resolve()
    if not sqlite_path.exists():
        print(f'ERROR: SQLite database not found: {sqlite_path}', file=sys.stderr)
        return 2
    database_url = args.database_url.strip() or ('' if args.dry_run else connection_url_from_prompt())
    report_path = Path(args.report).resolve()
    try:
        migrate(sqlite_path, database_url, args.reset, args.dry_run, report_path)
    except Exception as exc:
        print(f'ERROR: {exc}', file=sys.stderr)
        print(f'Report: {report_path}', file=sys.stderr)
        return 1
    print(f'Report: {report_path}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
