import importlib.util
from pathlib import Path

MODULE_PATH = Path(__file__).resolve().parents[1] / "app" / "db_compat.py"
spec = importlib.util.spec_from_file_location("db_compat_standalone", MODULE_PATH)
module = importlib.util.module_from_spec(spec)
assert spec and spec.loader
spec.loader.exec_module(module)
translate_sql = module.translate_sql
translate_ddl = module.translate_ddl


def test_execute_path_translates_autoincrement():
    sql = """CREATE TABLE IF NOT EXISTS supplier_communications (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        supplier_id INTEGER NOT NULL
    )"""
    translated = translate_sql(sql)
    assert "AUTOINCREMENT" not in translated.upper()
    assert "GENERATED BY DEFAULT AS IDENTITY" in translated.upper()
    assert "PRIMARY KEY" in translated.upper()


def test_executescript_path_translates_autoincrement():
    translated = translate_ddl("CREATE TABLE x (id INTEGER PRIMARY KEY AUTOINCREMENT)")
    assert "AUTOINCREMENT" not in translated.upper()
    assert "GENERATED BY DEFAULT AS IDENTITY" in translated.upper()


def test_insert_or_ignore_translation():
    translated = translate_sql("INSERT OR IGNORE INTO branches(name) VALUES(?)")
    assert "INSERT OR IGNORE" not in translated.upper()
    assert "ON CONFLICT DO NOTHING" in translated.upper()
    assert "%s" in translated
