from __future__ import annotations

import os
import sqlite3
import shutil
import time
from datetime import datetime
from functools import wraps
from pathlib import Path
from typing import Any, Callable

from flask import flash, g, redirect, render_template, request, session, url_for, has_request_context
from werkzeug.security import check_password_hash, generate_password_hash

from . import app
from .db_compat import connect as connect_database, table_columns, table_exists, database_healthcheck, table_has_unique_constraint, execute_insert

BASE_DIR = Path(__file__).resolve().parent.parent
DB_PATH = Path(os.environ.get("PHARMA_DB_PATH", str(BASE_DIR / "pharmacy_finance.db"))).expanduser().resolve()
DATABASE_URL = os.environ.get("DATABASE_URL", "").strip()

PERMISSIONS = {
    "view_dashboard": "عرض لوحة التحكم",
    "view_revenue": "عرض الإيرادات",
    "add_revenue": "إضافة إيراد",
    "edit_revenue": "تعديل الإيرادات",
    "delete_revenue": "حذف الإيرادات",
    "view_expenses": "عرض المصروفات",
    "add_expense": "إضافة مصروف",
    "edit_expense": "تعديل المصروفات",
    "delete_expense": "حذف المصروفات",
    "view_suppliers": "عرض الموردين",
    "manage_suppliers": "إدارة الموردين",
    "add_payments": "تسجيل السدادات",
    "view_reports": "عرض التقارير",
    "manage_users": "عرض المستخدمين والصلاحيات",
    "manage_roles": "إدارة الأدوار والصلاحيات",
    "manage_departments": "إدارة الأقسام",
    "manage_jobs": "إدارة الوظائف",
    "manage_code_generator": "إدارة مولد الأكواد",
    "view_workflows": "عرض مركز سير العمل",
    "manage_workflows": "إدارة تعريفات سير العمل",
    "add_users": "إضافة مستخدمين",
    "edit_users": "تعديل المستخدمين وكلمات المرور",
    "view_audit": "عرض سجل النشاط",
    "view_event_history": "عرض مستكشف الأحداث",
    "view_error_center": "عرض مركز الأخطاء",
    "view_cashbox": "عرض الخزينة",
    "manage_cashbox": "إدارة رصيد افتتاح الخزينة",
    "manage_day_closing": "إقفال وإعادة فتح الأيام",
    "manage_settings": "إدارة الإعدادات والنسخ الاحتياطي",
    "manage_system_policies": "إدارة سياسات النظام",
    "view_approvals": "عرض مركز الاعتمادات",
    "manage_approvals": "إدارة مسارات الاعتماد",
    "approve_transactions": "اعتماد ورفض العمليات",
    "manage_financial_accounts": "إدارة الحسابات المالية",
    "manage_locations": "إدارة الفروع والمواقع",
    "view_inventory": "عرض المخزون",
    "manage_inventory": "إدارة الأصناف وأرصدة المخزون",
    "manage_stock_transfers": "إدارة تحويلات المخزون",
    "view_invoice_transfers": "عرض تحويلات الفواتير",
    "manage_invoice_transfers": "إدارة تحويلات الفواتير",
    "view_notifications": "عرض الإشعارات والمهام",
    "manage_tasks": "إدارة المهام",
    "manage_trash": "إدارة سلة المحذوفات",
    "view_external_debts": "عرض الديون الخارجية",
    "add_external_debts": "إضافة دين خارجي",
    "edit_external_debts": "تعديل الديون الخارجية",
    "pay_external_debts": "تسجيل سداد دين خارجي",
    "delete_external_debts": "حذف الديون الخارجية",
    "export_external_debts": "تصدير تقارير الديون الخارجية",
    "view_main_treasury": "عرض الخزينة الرئيسية للمخزن",
    "view_branch_treasuries": "عرض خزائن الفروع",
    "create_treasury_transfers": "إنشاء توريدات وتحويلات مالية",
    "receive_treasury_transfers": "استلام واعتماد التوريدات المالية",
    "transfer_from_main_treasury": "تحويل أموال من الخزينة الرئيسية للفروع",
    "export_treasury_reports": "تصدير تقارير الخزائن والتوريدات",
    "view_financial_reports": "عرض التقارير المالية",
    "manage_financial_adjustments": "إدارة التعديلات اليدوية للتقارير المالية",
    "export_financial_reports": "تصدير التقارير المالية",
    "view_employees": "عرض الموظفين",
    "add_employees": "إضافة موظفين",
    "edit_employees": "تعديل بيانات الموظفين",
    "manage_attendance": "إدارة حضور الموظفين",
    "manage_employee_finance": "إدارة السلف والخصومات والمكافآت",
    "manage_payroll": "إدارة رواتب الموظفين",
}


def get_db():
    if "db" not in g:
        g.db = connect_database(DATABASE_URL, DB_PATH, timeout=30)
    return g.db


@app.teardown_appcontext
def close_db(exc: BaseException | None) -> None:
    """Close the request connection and never leak an aborted transaction.

    Psycopg keeps a connection in failed-transaction state after an exception.
    Explicit rollback here protects the next request when a pooled connection is
    reused, while successful routes remain responsible for their own commit.
    """
    db = g.pop("db", None)
    if db is not None:
        if exc is not None:
            try:
                db.rollback()
            except Exception:
                app.logger.exception("Database rollback failed during request teardown")
        db.close()


def init_db() -> None:
    db = connect_database(DATABASE_URL, DB_PATH, timeout=30)
    db.executescript(
        """
        CREATE TABLE IF NOT EXISTS branches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE
        );

        CREATE TABLE IF NOT EXISTS users (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL,
            full_name TEXT NOT NULL,
            role TEXT NOT NULL DEFAULT 'user',
            branch_id INTEGER,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            FOREIGN KEY(branch_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS user_permissions (
            user_id INTEGER NOT NULL,
            permission TEXT NOT NULL,
            PRIMARY KEY(user_id, permission),
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS revenues (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount >= 0),
            invoice_count INTEGER NOT NULL DEFAULT 0 CHECK(invoice_count >= 0),
            revenue_date TEXT NOT NULL,
            payment_method TEXT NOT NULL,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS revenue_employee_splits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            revenue_id INTEGER NOT NULL,
            employee_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount >= 0),
            invoice_count INTEGER NOT NULL DEFAULT 0 CHECK(invoice_count >= 0),
            worked_hours REAL NOT NULL DEFAULT 0 CHECK(worked_hours >= 0),
            created_at TEXT NOT NULL,
            UNIQUE(revenue_id, employee_id),
            FOREIGN KEY(revenue_id) REFERENCES revenues(id) ON DELETE CASCADE,
            FOREIGN KEY(employee_id) REFERENCES employees(id)
        );

        CREATE TABLE IF NOT EXISTS financial_classifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            statement_section TEXT NOT NULL CHECK(statement_section IN ('INCOME_STATEMENT','BALANCE_SHEET_ASSET','BALANCE_SHEET_LIABILITY','EQUITY','CASH_FLOW')),
            normal_balance TEXT NOT NULL DEFAULT 'DEBIT' CHECK(normal_balance IN ('DEBIT','CREDIT')),
            is_active INTEGER NOT NULL DEFAULT 1,
            sort_order INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS expenses (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            expense_date TEXT NOT NULL,
            category TEXT NOT NULL,
            financial_classification TEXT NOT NULL DEFAULT 'OPERATING',
            classification_id INTEGER,
            asset_type TEXT,
            payment_method TEXT NOT NULL,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(classification_id) REFERENCES financial_classifications(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS suppliers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            phone TEXT,
            total_due REAL NOT NULL DEFAULT 0 CHECK(total_due >= 0),
            notes TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS supplier_location_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_id INTEGER NOT NULL,
            location_id INTEGER NOT NULL,
            opening_due REAL NOT NULL DEFAULT 0 CHECK(opening_due >= 0),
            credit_limit REAL NOT NULL DEFAULT 0 CHECK(credit_limit >= 0),
            notes TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            UNIQUE(supplier_id, location_id),
            FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
            FOREIGN KEY(location_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS supplier_invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_id INTEGER NOT NULL,
            supplier_account_id INTEGER NOT NULL,
            branch_id INTEGER NOT NULL,
            invoice_number TEXT NOT NULL,
            invoice_date TEXT NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            notes TEXT,
            created_by INTEGER,
            created_at TEXT NOT NULL,
            UNIQUE(supplier_account_id, invoice_number),
            FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
            FOREIGN KEY(supplier_account_id) REFERENCES supplier_location_accounts(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS supplier_payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            supplier_id INTEGER NOT NULL,
            branch_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            payment_date TEXT NOT NULL,
            payment_method TEXT NOT NULL,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS employees (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_no TEXT NOT NULL UNIQUE,
            full_name TEXT NOT NULL,
            phone TEXT,
            address TEXT,
            emergency_contact_name TEXT,
            emergency_contact_phone TEXT,
            employee_code TEXT,
            biometric_no TEXT,
            attendance_pin_hash TEXT,
            attendance_portal_enabled INTEGER NOT NULL DEFAULT 0,
            branch_id INTEGER,
            department TEXT,
            job_title TEXT,
            direct_manager TEXT,
            hire_date TEXT NOT NULL,
            work_start_date TEXT,
            contract_type TEXT NOT NULL DEFAULT 'permanent',
            employment_status TEXT NOT NULL DEFAULT 'active',
            shift_type TEXT NOT NULL DEFAULT 'full',
            daily_hours REAL NOT NULL DEFAULT 8,
            work_days TEXT,
            basic_salary REAL NOT NULL DEFAULT 0 CHECK(basic_salary >= 0),
            fixed_allowances REAL NOT NULL DEFAULT 0 CHECK(fixed_allowances >= 0),
            fixed_deductions REAL NOT NULL DEFAULT 0 CHECK(fixed_deductions >= 0),
            bank_name TEXT,
            bank_account TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS employee_attendance (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id INTEGER NOT NULL,
            work_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'present',
            check_in TEXT,
            check_out TEXT,
            overtime_hours REAL NOT NULL DEFAULT 0,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(employee_id, work_date),
            FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS employee_leaves (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id INTEGER NOT NULL,
            leave_type TEXT NOT NULL,
            start_date TEXT NOT NULL,
            end_date TEXT NOT NULL,
            days REAL NOT NULL DEFAULT 1,
            status TEXT NOT NULL DEFAULT 'approved',
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS employee_adjustments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id INTEGER NOT NULL,
            adjustment_type TEXT NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            adjustment_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'approved',
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS employee_payroll (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            employee_id INTEGER NOT NULL,
            payroll_month TEXT NOT NULL,
            basic_salary REAL NOT NULL DEFAULT 0,
            bonuses REAL NOT NULL DEFAULT 0,
            deductions REAL NOT NULL DEFAULT 0,
            advances REAL NOT NULL DEFAULT 0,
            net_salary REAL NOT NULL DEFAULT 0,
            status TEXT NOT NULL DEFAULT 'draft',
            paid_date TEXT,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            UNIQUE(employee_id, payroll_month),
            FOREIGN KEY(employee_id) REFERENCES employees(id) ON DELETE CASCADE,
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER,
            action TEXT NOT NULL,
            details TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS event_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            event_type TEXT NOT NULL,
            entity_type TEXT,
            entity_id INTEGER,
            payload_json TEXT,
            user_id INTEGER,
            branch_id INTEGER,
            status TEXT NOT NULL DEFAULT 'PUBLISHED',
            error_message TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS activity_timeline (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL,
            event_type TEXT NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            user_id INTEGER,
            branch_id INTEGER,
            metadata_json TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS error_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source TEXT NOT NULL,
            error_type TEXT NOT NULL,
            message TEXT NOT NULL,
            traceback_text TEXT,
            user_id INTEGER,
            branch_id INTEGER,
            request_path TEXT,
            resolved INTEGER NOT NULL DEFAULT 0,
            resolved_by INTEGER,
            resolved_at TEXT,
            created_at TEXT NOT NULL,
            FOREIGN KEY(user_id) REFERENCES users(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS customer_groups (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL UNIQUE,
            discount_percent REAL NOT NULL DEFAULT 0 CHECK(discount_percent BETWEEN 0 AND 100),
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS customers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            customer_no TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            phone TEXT,
            email TEXT,
            address TEXT,
            tax_no TEXT,
            customer_group_id INTEGER,
            credit_limit REAL NOT NULL DEFAULT 0 CHECK(credit_limit >= 0),
            opening_balance REAL NOT NULL DEFAULT 0,
            is_active INTEGER NOT NULL DEFAULT 1,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            FOREIGN KEY(customer_group_id) REFERENCES customer_groups(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS sales_invoices (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_no TEXT NOT NULL UNIQUE,
            branch_id INTEGER NOT NULL,
            customer_id INTEGER,
            invoice_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','PENDING_APPROVAL','APPROVED','POSTED','CANCELLED')),
            subtotal REAL NOT NULL DEFAULT 0 CHECK(subtotal >= 0),
            discount_amount REAL NOT NULL DEFAULT 0 CHECK(discount_amount >= 0),
            tax_amount REAL NOT NULL DEFAULT 0 CHECK(tax_amount >= 0),
            total_amount REAL NOT NULL DEFAULT 0 CHECK(total_amount >= 0),
            payment_method TEXT NOT NULL DEFAULT 'CASH',
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(customer_id) REFERENCES customers(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS sales_invoice_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            invoice_id INTEGER NOT NULL,
            item_name TEXT NOT NULL,
            item_code TEXT,
            quantity REAL NOT NULL CHECK(quantity > 0),
            unit_price REAL NOT NULL CHECK(unit_price >= 0),
            discount_percent REAL NOT NULL DEFAULT 0 CHECK(discount_percent BETWEEN 0 AND 100),
            tax_percent REAL NOT NULL DEFAULT 0 CHECK(tax_percent BETWEEN 0 AND 100),
            line_total REAL NOT NULL DEFAULT 0 CHECK(line_total >= 0),
            FOREIGN KEY(invoice_id) REFERENCES sales_invoices(id) ON DELETE CASCADE
        );

        CREATE TABLE IF NOT EXISTS cashbox_openings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id INTEGER NOT NULL,
            opening_date TEXT NOT NULL,
            amount REAL NOT NULL CHECK(amount >= 0),
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            UNIQUE(branch_id, opening_date),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS day_closings (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id INTEGER NOT NULL,
            closing_date TEXT NOT NULL,
            is_closed INTEGER NOT NULL DEFAULT 1,
            closed_by INTEGER NOT NULL,
            closed_at TEXT NOT NULL,
            reopened_by INTEGER,
            reopened_at TEXT,
            notes TEXT,
            UNIQUE(branch_id, closing_date),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(closed_by) REFERENCES users(id),
            FOREIGN KEY(reopened_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS settings (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL DEFAULT ''
        );

        CREATE TABLE IF NOT EXISTS system_policies (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            category TEXT NOT NULL,
            rule_key TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            value TEXT NOT NULL,
            default_value TEXT NOT NULL,
            data_type TEXT NOT NULL CHECK(data_type IN ('boolean','integer','decimal','string','json')),
            description TEXT,
            is_editable INTEGER NOT NULL DEFAULT 1,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            updated_by INTEGER,
            FOREIGN KEY(updated_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS policy_change_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            policy_id INTEGER NOT NULL,
            rule_key TEXT NOT NULL,
            old_value TEXT,
            new_value TEXT NOT NULL,
            changed_by INTEGER,
            changed_at TEXT NOT NULL,
            reason TEXT,
            FOREIGN KEY(policy_id) REFERENCES system_policies(id),
            FOREIGN KEY(changed_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS financial_accounts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            branch_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            account_type TEXT NOT NULL DEFAULT 'CASH',
            is_active INTEGER NOT NULL DEFAULT 1,
            notes TEXT,
            created_at TEXT NOT NULL,
            UNIQUE(branch_id, name),
            FOREIGN KEY(branch_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            sku TEXT UNIQUE,
            unit TEXT NOT NULL DEFAULT 'علبة',
            is_active INTEGER NOT NULL DEFAULT 1,
            notes TEXT,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS inventory_balances (
            product_id INTEGER NOT NULL,
            location_id INTEGER NOT NULL,
            quantity REAL NOT NULL DEFAULT 0 CHECK(quantity >= 0),
            updated_at TEXT NOT NULL,
            PRIMARY KEY(product_id, location_id),
            FOREIGN KEY(product_id) REFERENCES products(id),
            FOREIGN KEY(location_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS stock_transfers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transfer_number TEXT NOT NULL UNIQUE,
            from_location_id INTEGER NOT NULL,
            to_location_id INTEGER NOT NULL,
            transfer_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SENT','RECEIVED','CANCELLED')),
            notes TEXT,
            created_by INTEGER NOT NULL,
            sent_by INTEGER,
            sent_at TEXT,
            received_by INTEGER,
            received_at TEXT,
            created_at TEXT NOT NULL,
            CHECK(from_location_id <> to_location_id),
            FOREIGN KEY(from_location_id) REFERENCES branches(id),
            FOREIGN KEY(to_location_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id),
            FOREIGN KEY(sent_by) REFERENCES users(id),
            FOREIGN KEY(received_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS stock_transfer_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transfer_id INTEGER NOT NULL,
            product_id INTEGER NOT NULL,
            quantity_sent REAL NOT NULL CHECK(quantity_sent > 0),
            quantity_received REAL,
            unit_cost REAL NOT NULL DEFAULT 0 CHECK(unit_cost >= 0),
            notes TEXT,
            UNIQUE(transfer_id, product_id),
            FOREIGN KEY(transfer_id) REFERENCES stock_transfers(id) ON DELETE CASCADE,
            FOREIGN KEY(product_id) REFERENCES products(id)
        );



        CREATE TABLE IF NOT EXISTS invoice_transfers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transfer_number TEXT NOT NULL UNIQUE,
            invoice_number TEXT NOT NULL,
            supplier_name TEXT,
            invoice_date TEXT NOT NULL,
            total_amount REAL NOT NULL DEFAULT 0 CHECK(total_amount >= 0),
            from_location_id INTEGER NOT NULL,
            to_location_id INTEGER NOT NULL,
            transfer_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SENT','RECEIVED','CANCELLED')),
            notes TEXT,
            created_by INTEGER NOT NULL,
            sent_by INTEGER,
            sent_at TEXT,
            received_by INTEGER,
            received_at TEXT,
            created_at TEXT NOT NULL,
            CHECK(from_location_id <> to_location_id),
            FOREIGN KEY(from_location_id) REFERENCES branches(id),
            FOREIGN KEY(to_location_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id),
            FOREIGN KEY(sent_by) REFERENCES users(id),
            FOREIGN KEY(received_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS notifications (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            message TEXT NOT NULL,
            notification_type TEXT NOT NULL DEFAULT 'INFO',
            priority TEXT NOT NULL DEFAULT 'NORMAL',
            location_id INTEGER,
            user_id INTEGER,
            reference_type TEXT,
            reference_id INTEGER,
            is_read INTEGER NOT NULL DEFAULT 0,
            created_at TEXT NOT NULL,
            FOREIGN KEY(location_id) REFERENCES branches(id),
            FOREIGN KEY(user_id) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS treasury_transfers (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transfer_number TEXT NOT NULL UNIQUE,
            from_account_id INTEGER NOT NULL,
            to_account_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            transfer_date TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SENT','RECEIVED','CANCELLED')),
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            sent_by INTEGER,
            sent_at TEXT,
            received_by INTEGER,
            received_at TEXT,
            FOREIGN KEY(from_account_id) REFERENCES financial_accounts(id),
            FOREIGN KEY(to_account_id) REFERENCES financial_accounts(id),
            FOREIGN KEY(created_by) REFERENCES users(id),
            FOREIGN KEY(sent_by) REFERENCES users(id),
            FOREIGN KEY(received_by) REFERENCES users(id),
            CHECK(from_account_id <> to_account_id)
        );

        CREATE TABLE IF NOT EXISTS tasks (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            title TEXT NOT NULL,
            description TEXT,
            location_id INTEGER,
            assigned_user_id INTEGER,
            task_type TEXT NOT NULL DEFAULT 'GENERAL',
            reference_type TEXT,
            reference_id INTEGER,
            status TEXT NOT NULL DEFAULT 'OPEN' CHECK(status IN ('OPEN','COMPLETED','CANCELLED')),
            priority TEXT NOT NULL DEFAULT 'NORMAL',
            created_by INTEGER,
            created_at TEXT NOT NULL,
            completed_by INTEGER,
            completed_at TEXT,
            FOREIGN KEY(location_id) REFERENCES branches(id),
            FOREIGN KEY(assigned_user_id) REFERENCES users(id),
            FOREIGN KEY(created_by) REFERENCES users(id),
            FOREIGN KEY(completed_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS quick_notes (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            note_text TEXT NOT NULL,
            user_id INTEGER NOT NULL,
            location_id INTEGER,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
            FOREIGN KEY(location_id) REFERENCES branches(id)
        );

        CREATE TABLE IF NOT EXISTS trash_bin (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            module TEXT NOT NULL,
            record_id INTEGER NOT NULL,
            record_name TEXT NOT NULL,
            data_json TEXT NOT NULL,
            related_json TEXT,
            deleted_by INTEGER NOT NULL,
            deleted_at TEXT NOT NULL,
            reason TEXT,
            FOREIGN KEY(deleted_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS external_debts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            reference_no TEXT NOT NULL UNIQUE,
            branch_id INTEGER NOT NULL,
            party_name TEXT NOT NULL,
            party_type TEXT NOT NULL CHECK(party_type IN ('INDIVIDUAL','EMPLOYEE','COMPANY','GOVERNMENT','OTHER')),
            debt_type TEXT NOT NULL CHECK(debt_type IN ('RECEIVABLE','PAYABLE')),
            amount REAL NOT NULL CHECK(amount > 0),
            account_id INTEGER NOT NULL,
            debt_date TEXT NOT NULL,
            due_date TEXT,
            reason_type TEXT NOT NULL DEFAULT 'OTHER',
            reason_details TEXT,
            phone TEXT,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(account_id) REFERENCES financial_accounts(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS external_debt_payments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            debt_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount > 0),
            account_id INTEGER NOT NULL,
            payment_date TEXT NOT NULL,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(debt_id) REFERENCES external_debts(id),
            FOREIGN KEY(account_id) REFERENCES financial_accounts(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );

        CREATE TABLE IF NOT EXISTS financial_ledger (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            transaction_number TEXT NOT NULL UNIQUE,
            branch_id INTEGER NOT NULL,
            account_id INTEGER NOT NULL,
            transaction_type TEXT NOT NULL,
            direction TEXT NOT NULL CHECK(direction IN ('IN','OUT')),
            amount REAL NOT NULL CHECK(amount > 0),
            transaction_date TEXT NOT NULL,
            reference_type TEXT NOT NULL,
            reference_id INTEGER NOT NULL,
            notes TEXT,
            created_by INTEGER NOT NULL,
            created_at TEXT NOT NULL,
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(account_id) REFERENCES financial_accounts(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );
        """
    )
    for name in ("الفرع الأول", "الفرع الثاني", "الفرع الثالث"):
        db.execute("INSERT INTO branches(name) VALUES(?) ON CONFLICT DO NOTHING", (name,))
    # v5.8.7: عدد الفواتير وتقسيم أداء الإيراد على الموظفين
    revenue_cols = table_columns(db, "revenues")
    if "invoice_count" not in revenue_cols:
        db.execute("ALTER TABLE revenues ADD COLUMN invoice_count INTEGER NOT NULL DEFAULT 0")
    db.executescript("""
        CREATE TABLE IF NOT EXISTS revenue_employee_splits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            revenue_id INTEGER NOT NULL,
            employee_id INTEGER NOT NULL,
            amount REAL NOT NULL CHECK(amount >= 0),
            invoice_count INTEGER NOT NULL DEFAULT 0 CHECK(invoice_count >= 0),
            worked_hours REAL NOT NULL DEFAULT 0 CHECK(worked_hours >= 0),
            created_at TEXT NOT NULL,
            UNIQUE(revenue_id, employee_id),
            FOREIGN KEY(revenue_id) REFERENCES revenues(id) ON DELETE CASCADE,
            FOREIGN KEY(employee_id) REFERENCES employees(id)
        );
        CREATE INDEX IF NOT EXISTS idx_revenue_employee_splits_revenue ON revenue_employee_splits(revenue_id);
        CREATE INDEX IF NOT EXISTS idx_revenue_employee_splits_employee ON revenue_employee_splits(employee_id);
    """)

    # v2.6: تحويل الفروع إلى مواقع وإضافة المخزن الرئيسي
    branch_cols = table_columns(db, "branches")
    if "location_type" not in branch_cols:
        db.execute("ALTER TABLE branches ADD COLUMN location_type TEXT NOT NULL DEFAULT 'BRANCH'")
    if "code" not in branch_cols:
        db.execute("ALTER TABLE branches ADD COLUMN code TEXT")
    if "is_active" not in branch_cols:
        db.execute("ALTER TABLE branches ADD COLUMN is_active INTEGER NOT NULL DEFAULT 1")
    db.execute("INSERT INTO branches(name,location_type,code,is_active) VALUES(?,?,?,1) ON CONFLICT DO NOTHING", ("المخزن الرئيسي", "MAIN_WAREHOUSE", "WH-MAIN"))

    # ربط سدادات الموردين بحساب المورد في الموقع
    payment_cols = table_columns(db, "supplier_payments")
    if "supplier_account_id" not in payment_cols:
        db.execute("ALTER TABLE supplier_payments ADD COLUMN supplier_account_id INTEGER")

    warehouse = db.execute("SELECT id FROM branches WHERE location_type='MAIN_WAREHOUSE' ORDER BY id LIMIT 1").fetchone()
    if warehouse:
        warehouse_id = warehouse[0]
        for sup in db.execute("SELECT id,total_due,notes,created_at FROM suppliers").fetchall():
            db.execute("""INSERT INTO supplier_location_accounts
                (supplier_id,location_id,opening_due,credit_limit,notes,is_active,created_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT DO NOTHING""",
                (sup[0],warehouse_id,sup[1] or 0,0,"رصيد مرحّل من النسخة السابقة",1,sup[3] or now()))
        for pay in db.execute("SELECT id,supplier_id FROM supplier_payments WHERE supplier_account_id IS NULL").fetchall():
            acc=db.execute("SELECT id FROM supplier_location_accounts WHERE supplier_id=? AND location_id=?",(pay[1],warehouse_id)).fetchone()
            if acc: db.execute("UPDATE supplier_payments SET supplier_account_id=? WHERE id=?",(acc[0],pay[0]))

    # v4.4: إدارة النظام وربط المستخدمين بالموظفين والأدوار
    db.executescript("""
        CREATE TABLE IF NOT EXISTS roles (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            code TEXT NOT NULL UNIQUE,
            description TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS role_permissions (
            role_id INTEGER NOT NULL,
            permission TEXT NOT NULL,
            PRIMARY KEY(role_id, permission),
            FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS departments (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL UNIQUE,
            description TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS jobs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL UNIQUE,
            description TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS code_sequences (
            entity_key TEXT PRIMARY KEY,
            label TEXT NOT NULL,
            prefix TEXT NOT NULL,
            padding INTEGER NOT NULL DEFAULT 5,
            next_number INTEGER NOT NULL DEFAULT 1,
            updated_at TEXT
        );
        CREATE TABLE IF NOT EXISTS workflow_definitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            entity_type TEXT NOT NULL,
            description TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS workflow_states (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_id INTEGER NOT NULL,
            code TEXT NOT NULL,
            name TEXT NOT NULL,
            sort_order INTEGER NOT NULL DEFAULT 0,
            is_initial INTEGER NOT NULL DEFAULT 0,
            is_final INTEGER NOT NULL DEFAULT 0,
            UNIQUE(workflow_id, code),
            FOREIGN KEY(workflow_id) REFERENCES workflow_definitions(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS workflow_transitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_id INTEGER NOT NULL,
            from_state_code TEXT NOT NULL,
            to_state_code TEXT NOT NULL,
            action_name TEXT NOT NULL,
            required_permission TEXT,
            is_active INTEGER NOT NULL DEFAULT 1,
            UNIQUE(workflow_id, from_state_code, to_state_code),
            FOREIGN KEY(workflow_id) REFERENCES workflow_definitions(id) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS workflow_instances (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            workflow_id INTEGER NOT NULL,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL,
            reference_no TEXT,
            current_state_code TEXT NOT NULL,
            branch_id INTEGER,
            created_by INTEGER,
            created_at TEXT NOT NULL,
            updated_at TEXT NOT NULL,
            UNIQUE(workflow_id, entity_type, entity_id),
            FOREIGN KEY(workflow_id) REFERENCES workflow_definitions(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(created_by) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS workflow_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            instance_id INTEGER NOT NULL,
            from_state_code TEXT,
            to_state_code TEXT NOT NULL,
            action_name TEXT NOT NULL,
            notes TEXT,
            changed_by INTEGER,
            changed_at TEXT NOT NULL,
            FOREIGN KEY(instance_id) REFERENCES workflow_instances(id) ON DELETE CASCADE,
            FOREIGN KEY(changed_by) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS approval_definitions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            code TEXT NOT NULL UNIQUE,
            name TEXT NOT NULL,
            entity_type TEXT NOT NULL,
            description TEXT,
            min_amount REAL,
            max_amount REAL,
            required_permission TEXT NOT NULL DEFAULT 'approve_transactions',
            branch_scope TEXT NOT NULL DEFAULT 'ANY' CHECK(branch_scope IN ('ANY','SAME_BRANCH','MAIN_WAREHOUSE')),
            is_active INTEGER NOT NULL DEFAULT 1,
            created_at TEXT NOT NULL
        );
        CREATE TABLE IF NOT EXISTS approval_requests (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            definition_id INTEGER NOT NULL,
            entity_type TEXT NOT NULL,
            entity_id INTEGER NOT NULL,
            reference_no TEXT,
            amount REAL,
            branch_id INTEGER,
            status TEXT NOT NULL DEFAULT 'PENDING' CHECK(status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
            current_step INTEGER NOT NULL DEFAULT 1,
            requested_by INTEGER NOT NULL,
            requested_at TEXT NOT NULL,
            decided_by INTEGER,
            decided_at TEXT,
            decision_note TEXT,
            FOREIGN KEY(definition_id) REFERENCES approval_definitions(id),
            FOREIGN KEY(branch_id) REFERENCES branches(id),
            FOREIGN KEY(requested_by) REFERENCES users(id),
            FOREIGN KEY(decided_by) REFERENCES users(id)
        );
        CREATE TABLE IF NOT EXISTS approval_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            request_id INTEGER NOT NULL,
            action TEXT NOT NULL CHECK(action IN ('REQUESTED','APPROVED','REJECTED','CANCELLED','RETURNED')),
            from_status TEXT,
            to_status TEXT NOT NULL,
            note TEXT,
            acted_by INTEGER,
            acted_at TEXT NOT NULL,
            FOREIGN KEY(request_id) REFERENCES approval_requests(id) ON DELETE CASCADE,
            FOREIGN KEY(acted_by) REFERENCES users(id)
        );
    """)
    user_cols = table_columns(db, "users")
    if "employee_id" not in user_cols:
        db.execute("ALTER TABLE users ADD COLUMN employee_id INTEGER")
    if "role_id" not in user_cols:
        db.execute("ALTER TABLE users ADD COLUMN role_id INTEGER")

    # v5.7.1: safe administration-center relationships (additive migration only)
    department_cols = table_columns(db, "departments")
    if "branch_id" not in department_cols:
        db.execute("ALTER TABLE departments ADD COLUMN branch_id INTEGER")
    employee_cols = table_columns(db, "employees")
    if "department_id" not in employee_cols:
        db.execute("ALTER TABLE employees ADD COLUMN department_id INTEGER")
    if "job_id" not in employee_cols:
        db.execute("ALTER TABLE employees ADD COLUMN job_id INTEGER")
    # v5.7.4: توسيع الملف الوظيفي ببيانات عملية للموارد البشرية
    hr_employee_columns = {
        "emergency_contact_name": "TEXT",
        "emergency_contact_phone": "TEXT",
        "employee_code": "TEXT",
        "biometric_no": "TEXT",
        "attendance_pin_hash": "TEXT",
        "attendance_portal_enabled": "INTEGER NOT NULL DEFAULT 0",
        "direct_manager": "TEXT",
        "work_start_date": "TEXT",
        "contract_type": "TEXT NOT NULL DEFAULT 'permanent'",
        "employment_status": "TEXT NOT NULL DEFAULT 'active'",
        "shift_type": "TEXT NOT NULL DEFAULT 'full'",
        "daily_hours": "REAL NOT NULL DEFAULT 8",
        "work_days": "TEXT",
        "fixed_allowances": "REAL NOT NULL DEFAULT 0",
        "fixed_deductions": "REAL NOT NULL DEFAULT 0",
        "bank_name": "TEXT",
        "bank_account": "TEXT",
    }
    for column, ddl in hr_employee_columns.items():
        if column not in employee_cols:
            db.execute(f"ALTER TABLE employees ADD COLUMN {column} {ddl}")
    db.execute("UPDATE employees SET work_start_date=hire_date WHERE work_start_date IS NULL OR work_start_date='' ")
    db.execute("UPDATE employees SET employment_status=CASE WHEN is_active=1 THEN 'active' ELSE 'suspended' END WHERE employment_status IS NULL OR employment_status='' ")
    branch_cols = table_columns(db, "branches")
    if "is_main" not in branch_cols:
        db.execute("ALTER TABLE branches ADD COLUMN is_main INTEGER NOT NULL DEFAULT 0")

    # Backfill new references from legacy text fields without removing legacy columns.
    db.execute("""UPDATE employees SET department_id=(SELECT d.id FROM departments d WHERE d.name=employees.department)
                  WHERE department_id IS NULL AND department IS NOT NULL""")
    db.execute("""UPDATE employees SET job_id=(SELECT j.id FROM jobs j WHERE j.name=employees.job_title)
                  WHERE job_id IS NULL AND job_title IS NOT NULL""")
    for name, code, description in (
        ("مدير النظام", "ADMIN", "صلاحيات كاملة على النظام"),
        ("مدير فرع", "BRANCH_MANAGER", "إدارة عمليات الفرع"),
        ("محاسب", "ACCOUNTANT", "العمليات والتقارير المالية"),
        ("صيدلي", "PHARMACIST", "عمليات الصيدلية اليومية"),
        ("كاشير", "CASHIER", "المبيعات والتحصيل"),
        ("أمين مخزن", "STOREKEEPER", "المخزون والتحويلات"),
    ):
        db.execute("INSERT INTO roles(name,code,description,is_active,created_at) VALUES(?,?,?,1,?) ON CONFLICT DO NOTHING", (name,code,description,now()))
    for name in ("الإدارة", "الحسابات", "المبيعات", "المخزون", "الصيدلية"):
        db.execute("INSERT INTO departments(name,is_active,created_at) VALUES(?,1,?) ON CONFLICT DO NOTHING", (name,now()))
    for code,name in (("JOB001","مدير عام"),("JOB002","مدير فرع"),("JOB003","صيدلي"),("JOB004","صيدلي مساعد"),("JOB005","محاسب"),("JOB006","كاشير"),("JOB007","أمين مخزن")):
        db.execute("INSERT INTO jobs(code,name,is_active,created_at) VALUES(?,?,1,?) ON CONFLICT DO NOTHING", (code,name,now()))
    for entity_key,label,prefix,padding in (("employee","الموظفون","EMP",5),("branch","الفروع","BR",3),("department","الأقسام","DEP",3),("job","الوظائف","JOB",3),("user","المستخدمون","USR",3),("supplier","الموردون","SUP",5),("customer","العملاء","CUS",5),("product","المنتجات","PRD",6),("sales_invoice","فواتير البيع","INV",8),("purchase_invoice","فواتير الشراء","PUR",8),("treasury_transfer","تحويلات الخزينة","TRF",6)):
        db.execute("INSERT INTO code_sequences(entity_key,label,prefix,padding,next_number,updated_at) VALUES(?,?,?,?,1,?) ON CONFLICT DO NOTHING",(entity_key,label,prefix,padding,now()))

    # v5.0: أساس محرك سير العمل
    db.execute("INSERT INTO workflow_definitions(code,name,entity_type,description,is_active,created_at) VALUES(?,?,?,?,1,?) ON CONFLICT DO NOTHING",
               ("TREASURY_TRANSFER", "تحويلات الخزينة", "treasury_transfer", "دورة اعتماد واستلام تحويلات الخزينة", now()))
    wf = db.execute("SELECT id FROM workflow_definitions WHERE code='TREASURY_TRANSFER'").fetchone()
    db.execute("""INSERT INTO approval_definitions
        (code,name,entity_type,description,min_amount,max_amount,required_permission,branch_scope,is_active,created_at)
        VALUES(?,?,?,?,?,?,?,?,1,?) ON CONFLICT DO NOTHING""",
        ("TREASURY_TRANSFER", "اعتماد تحويلات الخزينة", "treasury_transfer",
         "اعتماد التحويل قبل إرساله إلى خزينة الاستلام", None, None,
         "approve_transactions", "ANY", now()))

    if wf:
        for code,name,order_no,is_initial,is_final in (("DRAFT","مسودة",10,1,0),("SENT","مرسل",20,0,0),("WAITING_RECEIVE","بانتظار الاستلام",30,0,0),("RECEIVED","مستلم",40,0,1),("CANCELLED","ملغي",50,0,1)):
            db.execute("INSERT INTO workflow_states(workflow_id,code,name,sort_order,is_initial,is_final) VALUES(?,?,?,?,?,?) ON CONFLICT DO NOTHING",(wf[0],code,name,order_no,is_initial,is_final))
        for from_code,to_code,action,perm in (("DRAFT","SENT","إرسال","create_treasury_transfers"),("SENT","WAITING_RECEIVE","تحويل للاستلام","create_treasury_transfers"),("WAITING_RECEIVE","RECEIVED","تأكيد الاستلام","receive_treasury_transfers"),("DRAFT","CANCELLED","إلغاء","create_treasury_transfers"),("SENT","CANCELLED","إلغاء","create_treasury_transfers")):
            db.execute("INSERT INTO workflow_transitions(workflow_id,from_state_code,to_state_code,action_name,required_permission,is_active) VALUES(?,?,?,?,?,1) ON CONFLICT DO NOTHING",(wf[0],from_code,to_code,action,perm))

    # v5.6.3: POS product pricing fields used by the smart sales search
    product_cols = table_columns(db, "products")
    for column, ddl in (("sale_price", "REAL NOT NULL DEFAULT 0"),
                        ("default_discount_percent", "REAL NOT NULL DEFAULT 0"),
                        ("tax_percent", "REAL NOT NULL DEFAULT 0")):
        if column not in product_cols:
            db.execute(f"ALTER TABLE products ADD COLUMN {column} {ddl}")

    # v5.5: Enterprise Event Bus, Audit Center Pro and Error Center
    audit_cols = table_columns(db, "audit_log")
    for column, ddl in (("branch_id", "INTEGER"), ("entity_type", "TEXT"), ("entity_id", "INTEGER"),
                        ("action_code", "TEXT"), ("before_json", "TEXT"), ("after_json", "TEXT"),
                        ("metadata_json", "TEXT"), ("source", "TEXT")):
        if column not in audit_cols:
            db.execute(f"ALTER TABLE audit_log ADD COLUMN {column} {ddl}")
    db.execute("CREATE INDEX IF NOT EXISTS idx_event_history_entity ON event_history(entity_type,entity_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_timeline_entity ON activity_timeline(entity_type,entity_id,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_error_log_status ON error_log(resolved,created_at)")

    # v5.4: Notification & Task Engine migration
    notification_cols = table_columns(db, "notifications")
    for column, ddl in (("action_url", "TEXT"), ("event_key", "TEXT"), ("read_at", "TEXT")):
        if column not in notification_cols:
            db.execute(f"ALTER TABLE notifications ADD COLUMN {column} {ddl}")
    task_cols = table_columns(db, "tasks")
    for column, ddl in (("due_at", "TEXT"), ("action_url", "TEXT"), ("event_key", "TEXT"), ("assigned_permission", "TEXT")):
        if column not in task_cols:
            db.execute(f"ALTER TABLE tasks ADD COLUMN {column} {ddl}")

    # v5.8.3 — ملف المورد المالي المتقدم
    supplier_cols = table_columns(db, "suppliers")
    if "representative_name" not in supplier_cols:
        db.execute("ALTER TABLE suppliers ADD COLUMN representative_name TEXT")
    if "category" not in supplier_cols:
        db.execute("ALTER TABLE suppliers ADD COLUMN category TEXT NOT NULL DEFAULT 'أخرى'")
    if "rating" not in supplier_cols:
        db.execute("ALTER TABLE suppliers ADD COLUMN rating INTEGER NOT NULL DEFAULT 3")
    if "grace_days" not in supplier_cols:
        db.execute("ALTER TABLE suppliers ADD COLUMN grace_days INTEGER NOT NULL DEFAULT 30")

    # v5.8.6 — الإدارة النهائية للموردين
    supplier_cols = table_columns(db, "suppliers")
    for column, ddl in (("supplier_code", "TEXT"), ("is_archived", "INTEGER NOT NULL DEFAULT 0"),
                        ("internal_notes", "TEXT"), ("payment_methods", "TEXT NOT NULL DEFAULT 'نقدي,تحويل,صك'"),
                        ("credit_limit", "REAL NOT NULL DEFAULT 0")):
        if column not in supplier_cols:
            db.execute(f"ALTER TABLE suppliers ADD COLUMN {column} {ddl}")
    for row in db.execute("SELECT id FROM suppliers WHERE supplier_code IS NULL OR supplier_code='' ORDER BY id").fetchall():
        db.execute("UPDATE suppliers SET supplier_code=? WHERE id=?", (f"SUP-{int(row[0]):06d}", row[0]))
    db.execute("CREATE UNIQUE INDEX IF NOT EXISTS idx_suppliers_code ON suppliers(supplier_code)")
    db.execute("""CREATE TABLE IF NOT EXISTS supplier_communications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id INTEGER NOT NULL, communication_date TEXT NOT NULL,
        communication_type TEXT NOT NULL, contact_person TEXT, notes TEXT NOT NULL, created_by INTEGER NOT NULL,
        created_at TEXT NOT NULL, FOREIGN KEY(supplier_id) REFERENCES suppliers(id), FOREIGN KEY(created_by) REFERENCES users(id))""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_supplier_communications_supplier ON supplier_communications(supplier_id,communication_date)")

    # v5.8.1 — فواتير المورد الموحدة حسب الموقع وربط السداد بالفاتورة
    db.execute("""CREATE TABLE IF NOT EXISTS supplier_invoices (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id INTEGER NOT NULL,
        supplier_account_id INTEGER NOT NULL, branch_id INTEGER NOT NULL,
        invoice_number TEXT NOT NULL, invoice_date TEXT NOT NULL,
        amount REAL NOT NULL CHECK(amount > 0), notes TEXT, created_by INTEGER,
        created_at TEXT NOT NULL, UNIQUE(supplier_account_id, invoice_number),
        FOREIGN KEY(supplier_id) REFERENCES suppliers(id),
        FOREIGN KEY(supplier_account_id) REFERENCES supplier_location_accounts(id),
        FOREIGN KEY(branch_id) REFERENCES branches(id), FOREIGN KEY(created_by) REFERENCES users(id))""")
    payment_cols = table_columns(db, "supplier_payments")
    if "invoice_id" not in payment_cols:
        db.execute("ALTER TABLE supplier_payments ADD COLUMN invoice_id INTEGER")
    invoice_cols = table_columns(db, "supplier_invoices")
    if "due_date" not in invoice_cols:
        db.execute("ALTER TABLE supplier_invoices ADD COLUMN due_date TEXT")
    db.execute("""UPDATE supplier_invoices SET due_date=date(invoice_date, '+' || COALESCE((SELECT grace_days FROM suppliers s WHERE s.id=supplier_invoices.supplier_id),30) || ' days') WHERE due_date IS NULL OR due_date=''""")

    defaults = {
        "company_name": "صيدلي ERP",
        "system_subtitle": "الإدارة المالية",
        "currency": "د.ل",
        "phone": "",
        "address": "",
        "system_version": "5.8.6",
        "release_name": "Final Supplier Management",
        "release_date": "2026-07-22",
        "database_version": "5.8.6",
        "developer_name": "Pharma ERP Development Team",
    }
    for key, value in defaults.items():
        db.execute("INSERT INTO settings(key,value) VALUES(?,?) ON CONFLICT DO NOTHING", (key, value))
    for key in ("system_version", "release_name", "release_date", "database_version"):
        db.execute("UPDATE settings SET value=? WHERE key=?", (defaults[key], key))

    from .rules import RulesService
    RulesService.seed_defaults(db, now())


    # ترقية آمنة لقاعدة البيانات القديمة
    for table in ("revenues", "expenses", "supplier_payments"):
        cols = table_columns(db, table)
        if "account_id" not in cols:
            db.execute(f"ALTER TABLE {table} ADD COLUMN account_id INTEGER")

    # v4.0: جدول التصنيفات المالية وربط المصروفات به
    db.execute("""CREATE TABLE IF NOT EXISTS financial_classifications (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        code TEXT NOT NULL UNIQUE,
        name TEXT NOT NULL,
        statement_section TEXT NOT NULL CHECK(statement_section IN ('INCOME_STATEMENT','BALANCE_SHEET_ASSET','BALANCE_SHEET_LIABILITY','EQUITY','CASH_FLOW')),
        normal_balance TEXT NOT NULL DEFAULT 'DEBIT' CHECK(normal_balance IN ('DEBIT','CREDIT')),
        is_active INTEGER NOT NULL DEFAULT 1,
        sort_order INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL
    )""")
    classification_defaults = (
        ("OPERATING", "مصروف تشغيلي", "INCOME_STATEMENT", "DEBIT", 10),
        ("ASSET", "أصل", "BALANCE_SHEET_ASSET", "DEBIT", 20),
        ("LIABILITY", "التزام / خصم", "BALANCE_SHEET_LIABILITY", "CREDIT", 30),
    )
    for code, name, section, normal_balance, sort_order in classification_defaults:
        db.execute("""INSERT INTO financial_classifications(code,name,statement_section,normal_balance,is_active,sort_order,created_at)
                      VALUES(?,?,?,?,1,?,?)
                      ON CONFLICT(code) DO UPDATE SET name=excluded.name,statement_section=excluded.statement_section,
                      normal_balance=excluded.normal_balance,sort_order=excluded.sort_order""",
                   (code, name, section, normal_balance, sort_order, now()))

    expense_cols = table_columns(db, "expenses")
    if "financial_classification" not in expense_cols:
        db.execute("ALTER TABLE expenses ADD COLUMN financial_classification TEXT NOT NULL DEFAULT 'OPERATING'")
    if "classification_id" not in expense_cols:
        db.execute("ALTER TABLE expenses ADD COLUMN classification_id INTEGER")
    if "asset_type" not in expense_cols:
        db.execute("ALTER TABLE expenses ADD COLUMN asset_type TEXT")
    db.execute("UPDATE expenses SET financial_classification='OPERATING' WHERE financial_classification IS NULL OR financial_classification=''")
    db.execute("""UPDATE expenses SET classification_id=(
        SELECT id FROM financial_classifications fc WHERE fc.code=expenses.financial_classification
    ) WHERE classification_id IS NULL""")

    # v4.1: التعديلات اليدوية للتقارير المالية
    db.execute("""CREATE TABLE IF NOT EXISTS financial_report_adjustments (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        title TEXT NOT NULL,
        adjustment_type TEXT NOT NULL CHECK(adjustment_type IN ('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE','CASH_IN','CASH_OUT')),
        amount REAL NOT NULL CHECK(amount > 0),
        direction TEXT NOT NULL DEFAULT 'INCREASE' CHECK(direction IN ('INCREASE','DECREASE')),
        branch_id INTEGER,
        adjustment_date TEXT NOT NULL,
        notes TEXT,
        status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE','CANCELLED')),
        created_by INTEGER NOT NULL,
        created_at TEXT NOT NULL,
        cancelled_by INTEGER,
        cancelled_at TEXT,
        cancel_reason TEXT,
        FOREIGN KEY(branch_id) REFERENCES branches(id),
        FOREIGN KEY(created_by) REFERENCES users(id),
        FOREIGN KEY(cancelled_by) REFERENCES users(id)
    )""")
    db.execute("CREATE INDEX IF NOT EXISTS idx_financial_adjustments_date ON financial_report_adjustments(adjustment_date,adjustment_type,status)")

    # حساب نقدي افتراضي لكل فرع وترحيل الحركات القديمة إلى دفتر الحركة
    for branch in db.execute("SELECT id FROM branches").fetchall():
        db.execute("""INSERT INTO financial_accounts(branch_id,name,account_type,is_active,created_at)
                      VALUES(?,?,?,?,?)
                      ON CONFLICT(branch_id, name) DO NOTHING""",
                   (branch[0], "الخزينة النقدية", "CASH", 1, now()))
    for table, date_col, kind, direction in (("revenues","revenue_date","REVENUE","IN"),("expenses","expense_date","EXPENSE","OUT"),("supplier_payments","payment_date","SUPPLIER_PAYMENT","OUT")):
        rows=db.execute(f"SELECT id,branch_id,amount,{date_col},notes,created_by,created_at,account_id FROM {table}").fetchall()
        for row in rows:
            account_id=row[7] or db.execute("SELECT id FROM financial_accounts WHERE branch_id=? AND account_type='CASH' ORDER BY id LIMIT 1",(row[1],)).fetchone()[0]
            if not row[7]: db.execute(f"UPDATE {table} SET account_id=? WHERE id=?",(account_id,row[0]))
            db.execute("""INSERT INTO financial_ledger(transaction_number,branch_id,account_id,transaction_type,direction,amount,transaction_date,reference_type,reference_id,notes,created_by,created_at)
                          VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING""",
                       (f"TXN-{kind[:3]}-{row[0]:06d}",row[1],account_id,kind,direction,row[2],row[3],table,row[0],row[4],row[5],row[6]))

    # v2.5: السماح بتقسيم العملية الواحدة على أكثر من حساب مالي.
    # فحص القيد صار محايدًا للمحرك؛ PostgreSQL يستخدم pg_catalog وSQLite
    # يستخدم فهارس PRAGMA داخل طبقة قاعدة البيانات فقط.
    if table_has_unique_constraint(db, "financial_ledger", ("reference_type", "reference_id")):
        db.executescript("""
            ALTER TABLE financial_ledger RENAME TO financial_ledger_old;
            CREATE TABLE financial_ledger (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                transaction_number TEXT NOT NULL UNIQUE,
                branch_id INTEGER NOT NULL,
                account_id INTEGER NOT NULL,
                transaction_type TEXT NOT NULL,
                direction TEXT NOT NULL CHECK(direction IN ('IN','OUT')),
                amount REAL NOT NULL CHECK(amount > 0),
                transaction_date TEXT NOT NULL,
                reference_type TEXT NOT NULL,
                reference_id INTEGER NOT NULL,
                notes TEXT,
                created_by INTEGER NOT NULL,
                created_at TEXT NOT NULL,
                FOREIGN KEY(branch_id) REFERENCES branches(id),
                FOREIGN KEY(account_id) REFERENCES financial_accounts(id),
                FOREIGN KEY(created_by) REFERENCES users(id)
            );
            INSERT INTO financial_ledger SELECT * FROM financial_ledger_old;
            DROP TABLE financial_ledger_old;
            CREATE INDEX IF NOT EXISTS idx_ledger_reference ON financial_ledger(reference_type, reference_id);
            CREATE INDEX IF NOT EXISTS idx_ledger_account_date ON financial_ledger(account_id, transaction_date);
        """)

    db.execute("CREATE INDEX IF NOT EXISTS idx_employees_branch ON employees(branch_id,is_active,full_name)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_employee_attendance_date ON employee_attendance(employee_id,work_date)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_employee_adjustments_date ON employee_adjustments(employee_id,adjustment_date)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_employee_payroll_month ON employee_payroll(employee_id,payroll_month)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_inventory_location ON inventory_balances(location_id, product_id)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_transfers_status ON stock_transfers(status, transfer_date)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_invoice_transfers_status ON invoice_transfers(status, transfer_date)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_notifications_target ON notifications(location_id,user_id,is_read,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_tasks_target ON tasks(location_id,assigned_user_id,status,created_at)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_treasury_transfers_status ON treasury_transfers(status,transfer_date)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_external_debts_due ON external_debts(due_date,debt_type,branch_id)")
    db.execute("CREATE INDEX IF NOT EXISTS idx_external_debt_payments ON external_debt_payments(debt_id,payment_date)")

    # Stage 4.5: PostgreSQL performance indexes for the most frequently filtered,
    # joined and date-ranged business records. IF NOT EXISTS keeps startup idempotent.
    performance_indexes = (
        "CREATE INDEX IF NOT EXISTS idx_revenues_branch_date ON revenues(branch_id, revenue_date)",
        "CREATE INDEX IF NOT EXISTS idx_expenses_branch_date ON expenses(branch_id, expense_date)",
        "CREATE INDEX IF NOT EXISTS idx_supplier_accounts_supplier_location ON supplier_location_accounts(supplier_id, location_id)",
        "CREATE INDEX IF NOT EXISTS idx_supplier_invoices_supplier_date ON supplier_invoices(supplier_id, invoice_date)",
        "CREATE INDEX IF NOT EXISTS idx_supplier_invoices_branch_due ON supplier_invoices(branch_id, due_date)",
        "CREATE INDEX IF NOT EXISTS idx_supplier_payments_supplier_date ON supplier_payments(supplier_id, payment_date)",
        "CREATE INDEX IF NOT EXISTS idx_supplier_payments_branch_date ON supplier_payments(branch_id, payment_date)",
        "CREATE INDEX IF NOT EXISTS idx_sales_invoices_branch_date ON sales_invoices(branch_id, invoice_date)",
        "CREATE INDEX IF NOT EXISTS idx_sales_invoices_status_date ON sales_invoices(status, invoice_date)",
        "CREATE INDEX IF NOT EXISTS idx_sales_items_invoice ON sales_invoice_items(invoice_id)",
        "CREATE INDEX IF NOT EXISTS idx_stock_transfers_locations_date ON stock_transfers(from_location_id, to_location_id, transfer_date)",
        "CREATE INDEX IF NOT EXISTS idx_stock_transfer_items_transfer ON stock_transfer_items(transfer_id)",
        "CREATE INDEX IF NOT EXISTS idx_invoice_transfers_locations_date ON invoice_transfers(from_location_id, to_location_id, transfer_date)",
        "CREATE INDEX IF NOT EXISTS idx_treasury_transfers_accounts_date ON treasury_transfers(from_account_id, to_account_id, transfer_date)",
        "CREATE INDEX IF NOT EXISTS idx_external_debts_branch_date ON external_debts(branch_id, debt_date)",
        "CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at)",
        "CREATE INDEX IF NOT EXISTS idx_audit_log_user_created ON audit_log(user_id, created_at)",
        "CREATE INDEX IF NOT EXISTS idx_approval_requests_status_requested ON approval_requests(status, requested_at)",
        "CREATE INDEX IF NOT EXISTS idx_quick_notes_user_created ON quick_notes(user_id, created_at)",
    )
    for index_sql in performance_indexes:
        db.execute(index_sql)

    user_columns = table_columns(db, "users")
    if "must_change_password" not in user_columns:
        db.execute("ALTER TABLE users ADD COLUMN must_change_password INTEGER NOT NULL DEFAULT 0")

    # Bootstrap the first administrator only when the users table is truly empty.
    # Existing production databases may use a different administrator username,
    # so checking only for username='admin' can incorrectly block startup.
    existing_user = db.execute(
        "SELECT id, username, password_hash FROM users ORDER BY id LIMIT 1"
    ).fetchone()

    if not existing_user:
        bootstrap_password = os.environ.get("ADMIN_INITIAL_PASSWORD", "").strip()
        is_production = os.environ.get("APP_ENV", "development").strip().lower() == "production"
        if is_production and len(bootstrap_password) < 12:
            db.close()
            raise RuntimeError("First production startup requires ADMIN_INITIAL_PASSWORD with at least 12 characters.")
        if not bootstrap_password:
            import secrets
            bootstrap_password = secrets.token_urlsafe(16)
            credentials_file = BASE_DIR / "FIRST_RUN_ADMIN.txt"
            credentials_file.write_text(
                f"username=admin\npassword={bootstrap_password}\nغيّر كلمة المرور فور أول دخول.\n",
                encoding="utf-8",
            )
            try:
                credentials_file.chmod(0o600)
            except OSError:
                pass
        db.execute(
            "INSERT INTO users(username,password_hash,full_name,role,must_change_password,created_at) VALUES(?,?,?,?,?,?)",
            ("admin", generate_password_hash(bootstrap_password), "المدير الرئيسي", "admin", 1, now()),
        )
    else:
        legacy_admin = db.execute(
            "SELECT id,password_hash FROM users WHERE username='admin' ORDER BY id LIMIT 1"
        ).fetchone()
        if legacy_admin and check_password_hash(legacy_admin["password_hash"], "admin123"):
            db.execute("UPDATE users SET must_change_password=1 WHERE id=?", (legacy_admin["id"],))
    db.commit()
    db.close()


def sync_ledger(reference_type: str, reference_id: int, branch_id: int, account_id: int, transaction_type: str, direction: str, amount: float, transaction_date: str, notes: str, created_by: int) -> None:
    sync_ledger_splits(reference_type, reference_id, branch_id, transaction_type, direction, amount, transaction_date, notes, created_by, [(account_id, amount)])


def sync_ledger_splits(reference_type: str, reference_id: int, branch_id: int, transaction_type: str, direction: str, total_amount: float, transaction_date: str, notes: str, created_by: int, splits: list[tuple[int, float]]) -> None:
    db = get_db()
    clean = [(int(account_id), round(float(value), 2)) for account_id, value in splits if float(value) > 0]
    if not clean:
        raise ValueError("يجب تحديد حساب مالي واحد على الأقل.")
    split_total = round(sum(value for _, value in clean), 2)
    if round(float(total_amount), 2) != split_total:
        raise ValueError(f"مجموع التقسيم ({split_total:.2f}) لا يساوي قيمة العملية ({float(total_amount):.2f}).")
    valid_ids = {row["id"] for row in db.execute("SELECT id FROM financial_accounts WHERE branch_id=? AND is_active=1", (branch_id,)).fetchall()}
    if any(account_id not in valid_ids for account_id, _ in clean):
        raise ValueError("أحد الحسابات المالية غير صالح لهذا الفرع.")
    db.execute("DELETE FROM financial_ledger WHERE reference_type=? AND reference_id=?", (reference_type, reference_id))
    prefix = {"REVENUE":"REV", "EXPENSE":"EXP", "SUPPLIER_PAYMENT":"PAY", "EXTERNAL_DEBT":"EXTD", "EXTERNAL_DEBT_PAYMENT":"EXTP"}.get(transaction_type, "TXN")
    for index, (account_id, value) in enumerate(clean, 1):
        txno = f"TXN-{prefix}-{reference_id:06d}-{index:02d}"
        db.execute("""INSERT INTO financial_ledger(transaction_number,branch_id,account_id,transaction_type,direction,amount,transaction_date,reference_type,reference_id,notes,created_by,created_at)
                      VALUES(?,?,?,?,?,?,?,?,?,?,?,?)""",
                   (txno, branch_id, account_id, transaction_type, direction, value, transaction_date, reference_type, reference_id, notes, created_by, now()))


def parse_account_splits(form, branch_id: int, total_amount: float) -> list[tuple[int, float]]:
    account_ids = form.getlist("split_account_id")
    amounts = form.getlist("split_amount")
    if not account_ids:
        account_id = form.get("account_id", type=int)
        if not account_id:
            row = get_db().execute("SELECT id FROM financial_accounts WHERE branch_id=? AND is_active=1 ORDER BY CASE account_type WHEN 'CASH' THEN 0 ELSE 1 END,id LIMIT 1", (branch_id,)).fetchone()
            account_id = row["id"] if row else None
        return [(account_id, total_amount)] if account_id else []
    splits = []
    for raw_account, raw_amount in zip(account_ids, amounts):
        if not raw_account or not raw_amount:
            continue
        value = float(raw_amount)
        if value > 0:
            splits.append((int(raw_account), value))
    return splits


def delete_ledger(reference_type: str, reference_id: int) -> None:
    get_db().execute("DELETE FROM financial_ledger WHERE reference_type=? AND reference_id=?",(reference_type,reference_id))

def accounts_for_branch(branch_id: int):
    return get_db().execute("SELECT * FROM financial_accounts WHERE branch_id=? AND is_active=1 ORDER BY account_type,name",(branch_id,)).fetchall()

def insert_and_get_id(db: Any, sql: str, params: tuple[Any, ...] | list[Any] = (), returning: str = "id") -> int:
    """Execute an INSERT and return its generated key through the DB adapter."""
    return execute_insert(db, sql, params, returning=returning)


def now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M:%S")


def current_user() -> sqlite3.Row | None:
    """Return the signed-in user, loading it only once per request."""
    if hasattr(g, "_current_user_loaded"):
        return g._current_user

    user_id = session.get("user_id")
    user = None
    if user_id:
        user = get_db().execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()

    g._current_user = user
    g._current_user_loaded = True
    return user


def has_permission(permission: str) -> bool:
    """Check permissions with a request-local cache to avoid duplicate SQL."""
    cache = getattr(g, "_permission_cache", None)
    if cache is None:
        cache = {}
        g._permission_cache = cache
    if permission in cache:
        return cache[permission]

    user = current_user()
    allowed = False
    if user and user["is_active"]:
        if user["role"] == "admin":
            allowed = True
        else:
            row = get_db().execute(
                "SELECT 1 FROM user_permissions WHERE user_id = ? AND permission = ?",
                (user["id"], permission),
            ).fetchone()
            if row is not None:
                allowed = True
            elif "role_id" in user.keys() and user["role_id"]:
                row = get_db().execute(
                    "SELECT 1 FROM role_permissions WHERE role_id=? AND permission=?",
                    (user["role_id"], permission),
                ).fetchone()
                allowed = row is not None

    cache[permission] = allowed
    return allowed


def login_required(view: Callable[..., Any]) -> Callable[..., Any]:
    @wraps(view)
    def wrapped(*args: Any, **kwargs: Any) -> Any:
        if not current_user():
            return redirect(url_for("login"))
        return view(*args, **kwargs)

    return wrapped


def permission_required(permission: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]:
    def decorator(view: Callable[..., Any]) -> Callable[..., Any]:
        @wraps(view)
        def wrapped(*args: Any, **kwargs: Any) -> Any:
            if not has_permission(permission):
                flash("ليس لديك صلاحية لتنفيذ هذه العملية.", "danger")
                return redirect(url_for("dashboard"))
            return view(*args, **kwargs)

        return wrapped

    return decorator


def audit(action: str, details: str = "", *, action_code: str | None = None,
          entity_type: str | None = None, entity_id: int | None = None,
          before: Any | None = None, after: Any | None = None,
          metadata: Any | None = None, source: str = "web", commit: bool = True) -> None:
    import json
    user = current_user() if has_request_context() else None
    branch_id = user["branch_id"] if user and "branch_id" in user.keys() else None
    db = get_db()
    db.execute(
        """INSERT INTO audit_log(user_id,branch_id,action,action_code,details,entity_type,entity_id,
               before_json,after_json,metadata_json,source,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)""",
        (user["id"] if user else None, branch_id, action, action_code, details, entity_type, entity_id,
         json.dumps(before, ensure_ascii=False, default=str) if before is not None else None,
         json.dumps(after, ensure_ascii=False, default=str) if after is not None else None,
         json.dumps(metadata, ensure_ascii=False, default=str) if metadata is not None else None, source, now()),
    )
    if commit:
        db.commit()


def get_setting(key: str, default: str = "") -> str:
    row = get_db().execute("SELECT value FROM settings WHERE key = ?", (key,)).fetchone()
    return row["value"] if row else default


def all_settings() -> dict[str, str]:
    return {row["key"]: row["value"] for row in get_db().execute("SELECT key,value FROM settings").fetchall()}



def is_day_closed(branch_id: int, date_value: str) -> bool:
    row = get_db().execute(
        "SELECT is_closed FROM day_closings WHERE branch_id=? AND closing_date=?",
        (branch_id, date_value),
    ).fetchone()
    return bool(row and row["is_closed"])


def reject_if_day_closed(branch_id: int, date_value: str) -> bool:
    if is_day_closed(branch_id, date_value):
        flash("هذا اليوم مقفل لهذا الفرع. أعد فتحه من مركز القيادة قبل التعديل.", "danger")
        return True
    return False

def branch_filter_sql(alias: str = "") -> tuple[str, list[Any]]:
    user = current_user()
    prefix = f"{alias}." if alias else ""
    if user and user["role"] != "admin" and user["branch_id"]:
        return f" AND {prefix}branch_id = ?", [user["branch_id"]]
    return "", []


def create_notification(title: str, message: str, *, location_id: int | None = None, user_id: int | None = None, notification_type: str = "INFO", priority: str = "NORMAL", reference_type: str | None = None, reference_id: int | None = None, action_url: str | None = None, event_key: str | None = None, deduplicate: bool = False) -> int:
    from .notifications import NotificationService
    return NotificationService.create(get_db(), title=title, message=message, created_at=now(), location_id=location_id, user_id=user_id, notification_type=notification_type, priority=priority, reference_type=reference_type, reference_id=reference_id, action_url=action_url, event_key=event_key, deduplicate=deduplicate)

def create_task(title: str, description: str = "", *, location_id: int | None = None, assigned_user_id: int | None = None, assigned_permission: str | None = None, task_type: str = "GENERAL", reference_type: str | None = None, reference_id: int | None = None, priority: str = "NORMAL", due_at: str | None = None, action_url: str | None = None, event_key: str | None = None, deduplicate: bool = True) -> int:
    from .tasks import TaskService
    user = current_user()
    return TaskService.create(get_db(), title=title, description=description, created_at=now(), location_id=location_id, assigned_user_id=assigned_user_id, assigned_permission=assigned_permission, task_type=task_type, reference_type=reference_type, reference_id=reference_id, priority=priority, created_by=user["id"] if user else None, due_at=due_at, action_url=action_url, event_key=event_key, deduplicate=deduplicate)

def notification_scope() -> tuple[str, list[Any]]:
    user = current_user()
    if not user: return " AND 1=0", []
    if user["role"] == "admin": return "", []
    clauses=["user_id=?"]; params=[user["id"]]
    if user["branch_id"]:
        clauses.append("location_id=?"); params.append(user["branch_id"])
    return " AND (" + " OR ".join(clauses) + ")", params

def task_scope() -> tuple[str, list[Any]]:
    user = current_user()
    if not user: return " AND 1=0", []
    if user["role"] == "admin": return "", []
    clauses=["assigned_user_id=?"]; params=[user["id"]]
    if user["branch_id"]:
        clauses.append("location_id=?"); params.append(user["branch_id"])
    permission_rows = get_db().execute("SELECT permission FROM user_permissions WHERE user_id=?", (user["id"],)).fetchall()
    permissions = [row["permission"] for row in permission_rows]
    if user["role_id"]:
        permissions.extend(row["permission"] for row in get_db().execute("SELECT permission FROM role_permissions WHERE role_id=?", (user["role_id"],)).fetchall())
    if permissions:
        clauses.append("assigned_permission IN (" + ",".join("?" for _ in permissions) + ")")
        params.extend(permissions)
    return " AND (" + " OR ".join(clauses) + ")", params


@app.context_processor
def inject_globals() -> dict[str, Any]:
    user = current_user()
    notification_items = []
    unread_count = 0
    open_task_count = 0
    overdue_task_count = 0
    pending_approval_count = 0
    if user:
        db = get_db()
        nscope, nparams = notification_scope()
        notification_items = db.execute("SELECT * FROM notifications WHERE 1=1"+nscope+" ORDER BY is_read ASC,id DESC LIMIT 8", nparams).fetchall()
        unread_count = db.execute("SELECT COUNT(*) c FROM notifications WHERE is_read=0"+nscope, nparams).fetchone()["c"]
        tscope, tparams = task_scope()
        open_task_count = db.execute("SELECT COUNT(*) c FROM tasks WHERE status='OPEN'"+tscope, tparams).fetchone()["c"]
        overdue_task_count = db.execute("SELECT COUNT(*) c FROM tasks WHERE status='OPEN' AND due_at IS NOT NULL AND due_at < ?"+tscope, [now()]+tparams).fetchone()["c"]
        if has_permission("view_approvals"):
            pending_approval_count = db.execute("SELECT COUNT(*) c FROM approval_requests WHERE status='PENDING'").fetchone()["c"]
    return {
        "current_user": user,
        "has_permission": has_permission,
        "permissions_map": PERMISSIONS,
        "app_settings": all_settings() if user else {},
        "top_notifications": notification_items,
        "unread_notification_count": unread_count,
        "open_task_count": open_task_count,
        "overdue_task_count": overdue_task_count,
        "pending_approval_count": pending_approval_count,
    }
